apply plugin: 'com.android.application'

android {
    namespace "com.hyxen.adlocus"
    compileSdkVersion 35
    defaultConfig {
        applicationId "com.hyxen.adlocus"
        minSdkVersion 26
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        targetCompatibility 1.8
        sourceCompatibility 1.8
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    api 'com.android.support:appcompat-v7:26.1.0'
    api 'com.android.support.constraint:constraint-layout:1.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    implementation "androidx.security:security-crypto:1.1.0-alpha02"
//    implementation project(':adlocusaar')
    implementation 'io.reactivex.rxjava2:rxjava:2.0.6'
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.2.0'

    implementation("io.github.adlocushyxen:adlocusaar:4.1.52", {
        exclude group: 'com.google.android.gms', module: 'play-services-ads'
        exclude group: 'com.google.android.gms', module: 'play-services-base'
    })
    /*
    implementation("io.github.vfhhu:adlocusaar:4.1.50", {
        exclude group: 'com.google.android.gms', module: 'play-services-ads'
        exclude group: 'com.google.android.gms', module: 'play-services-base'
    })*/

//    api 'com.google.firebase:firebase-messaging:15.0.0'

//    implementation 'com.squareup.okhttp3:okhttp:4.2.0'

}
//apply plugin: 'com.google.gms.google-services'
